banner:
    location: classpath:/auxiliares/banner.txt
    
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sigecu?useSSL=false
    username: root
<<<<<<< HEAD
    password: naye
=======
    password: 'martinez'
>>>>>>> master
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy