banner:
    location: classpath:/auxiliares/banner.txt
    
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_sigecu?useSSL=false
    username: root
    password: naye
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy